const DummyData = [{
  id: "example-0",
  title: "레스토랑",
  description: "종업원과 대화하여 음식을 주문해보세요!", 
  img: "/images/theme/restaurant.jpg",
  mission: ["메뉴를 보고 종업원에게 주문하기", 
  "특별한 요청사항(예: 알레르기, 특별한 조리 방법) 전달하기", 
  "주문 후 확인하기(예: 주문한 음식을 잘 받았는지 확인)"],
},{
  title:"카페",
  id: "example-1",
  description: "오늘따라 눈에 띈 작은 카페에 방문해서 음료를 주문해보세요!", 
  img: "/images/theme/cafe.jpg",
  mission: ["원하는 음료와 사이즈 선택하기", 
  "추가 옵션(예: 샷 추가, 시럽 선택) 요청하기", 
  "주문 후 결제 및 음료 픽업"],
},{
  title:"상점",
  id: "example-2",
  description: "뿌연 먼지가 쌓였지만 복도 끝이 보이지 않는 마법같은 상점! 이번에 구매하게 될 물건은 무엇일까요?", 
  img: "/images/theme/shop.jpg",
  mission: ["필요한 물건을 점원에게 물어보기", 
  "물건에 대한 추가 정보(예: 가격, 품질) 질문하기", 
  "결제 시 다양한 결제 방법 선택 및 사용"],
},{
  id: "example-3",
  title:"호텔",
  description: "힐링이 가득한 휴식을 위해 호텔에 방문했어요!", 
  img: "/images/theme/hotel.jpg",
  mission: ["체크인 시 예약 확인 및 필요한 정보 제공", 
  "방에 대한 문의(예: 추가 베개, 룸 서비스) 하기", 
  "체크아웃 시 비용 확인 및 결제"],
},{
  id: "example-4",
  title:"미용실",
  description: "잡지를 보다가 방문하게된 미용실!", 
  img: "/images/theme/salon.jpg",
  mission: ["원하는 헤어스타일 설명", 
  "커트나 컬러에 대한 세부 사항 논의", 
  "스타일링 후 만족도 확인 및 추가 요청"],
},{
  id: "example-5",
  title:"도서관",
  description: "아.. 그 책 제목이 뭐더라? 간만에 도서관에 방문해봅시다!", 
  img: "/images/theme/library.jpg",
  mission: ["원하는 책이나 자료를 도서관 직원에게 물어보기", 
  "도서관 서비스(예: 프린트, 복사) 이용 방법 질문"],
},{
  id: "example-6",
  title:"대중교통",
  description: "어라 핸드폰이 방전됐어요.. 교통수단에 대한 정보를 사람들에게 물어봅시다!", 
  img: "/images/theme/traffic.jpg",
  mission: ["경로 또는 시간표에 대해 문의", 
  "목적지까지의 최적 경로 상담"],
},{
  id: "example-7",
  title:"예약",
  description: "캐치 테이블 구경하는데 먹고싶은 음식이 있다? 그럼 당장 예약해야죠 ㅇㅇ", 
  img: "/images/theme/reservation.jpg",
  mission: ["예약 가능한 시간과 인원 확인", 
  "특별한 요청사항(예: 창가 자리, 조용한 자리) 전달"],
}]

export default DummyData;